on: push

jobs:
  put:
    runs-on: ubuntu-latest
    steps:
      - name: Create Deployment
        uses: bobheadxi/deployments@v0.6.2
        id: deployment
        with:
          step: start
          token: ${{ github.token }}
          env: aws

      - uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - run: |
          aws s3 cp \
            ./install.sh s3://www.tea.xyz/pour.sh \
            --metadata-directive REPLACE \
            --cache-control no-cache,must-revalidate
      - run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.AWS_CF_DISTRIBUTION_ID }} \
            --paths / /pour.sh

      - name: Seal Deployment
        uses: bobheadxi/deployments@v0.6.2
        if: always()
        with:
          step: finish
          token: ${{ github.token }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
